/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package smsfinal;

import java.awt.Toolkit;
import static java.lang.Thread.sleep;

/**
 *
 * @author HiGHROLLER
 */
public class splashy extends javax.swing.JFrame {

    /**
     * Creates new form splashy
     */
    public splashy() {
        initComponents();
        iconMethod();
        new Thread()
        {
            @Override
            public void run()
            {
                for(int i=0;i<101;i++)
                {
                    try {
                        sleep(120);

                        jProgressBar1.setValue(i);
                        if(jProgressBar1.getValue()<=25){
                            txt_show.setText("Initializing modules.....");
                     
                        }else if(jProgressBar1.getValue()<=50){
                            txt_show.setText("Turning on modules.....");
                        }else if(jProgressBar1.getValue()<=75){
                            txt_show.setText("Loading modules........");
                        }else if(jProgressBar1.getValue()<=96){
                            txt_show.setText("Preparing desktop applications......");
                        }  else if(jProgressBar1.getValue()<=100){
                            txt_show.setText("Done Loading Modules.");
                             
                        }  
                        
                    } catch (InterruptedException ex) 
                    {
                        //Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    finally{
                            
                    }


                }
               logPanel m = new logPanel();
               
             close();
              m.setVisible(true);
     
            }     
        }.start();
         
    }
    public void close()
    {
        this.hide();
    }
     public void iconMethod()
    {
    this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("students.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        txt_show = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setString("");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 550, 10));

        txt_show.setForeground(new java.awt.Color(255, 255, 255));
        txt_show.setText("jLabel1");
        getContentPane().add(txt_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 220, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/attatchments/splash.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 300));

        setSize(new java.awt.Dimension(569, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splashy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splashy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splashy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splashy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel txt_show;
    // End of variables declaration//GEN-END:variables
}
